baseURL: "https://prasadsaurabh.github.io"
title: "Saurabh Prasad"
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - name: Papers
      url: /papers/
      weight: 1
    - name: Books
      url: /books/
      weight: 2
    - name: Research
      url: /research/
      weight: 3
    - name: Team
      url: /team/
      weight: 4
    - name: News
      url: /news/
      weight: 5
    - name: Teac
