baseURL: "https://prasadsaurabh.github.io"
title: "Saurabh Prasad"
pagination:
  pagerSize: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
  tag: tags

menu:
  main:
    - name: Papers
      url: /papers/
      weight: 1
    - name: Books
      url: /books/
      weight: 2
    - name: Research
      url: /research/
      weight: 3
    - name: Team
      url: /team/
      weight: 4
    - name: News
      url: /news/
      weight: 5
    - name: Teaching
      url: /teaching/
      weight: 6

params:
  description: "Machine Learning and Signal Processing Lab, University of Houston"
  author: Saurabh Prasad
  googleAnalyticsID: ""
  DateFormat: "January 2006"
  defaultTheme: light
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowAllPagesInArchive: false
  MainSections: ["papers","books"]
  ShowToc: false
  TocOpen: true
  assets:
    disableScrollBarStyle: true
  cover:
    hiddenInList: false
    hiddenInSingle: true
  label:
    text: "Saurabh Prasad"
    icon: /favicon.ico
    iconHeight: 35
  socialIcons:
    - name: Email
      url: mailto:sprasad2@uh.edu
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=g_FRerIAAAAJ
    - name: LinkedIn
      url: https://www.linkedin.com/in/saurabh-prasad-2675a217/
    - name: GitHub
      url: https://github.com/PrasadLab

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    startLevel: 2
